import React, {
  useRef, useEffect, useState, useCallback, memo,
} from 'react';
import { createPortal } from 'react-dom';
import DOMPurify from 'dompurify';
import {
  useArtifacts, updateArtifact, deleteArtifact, Artifact, loadArtifactContent,
} from '../services/artifactStore';
import { Icons } from '../constants';
import './ArtifactPanel.css';

const LANG_LABELS: Record<string, string> = {
  typescript: 'TypeScript', ts: 'TypeScript', tsx: 'TypeScript (React)',
  javascript: 'JavaScript', js: 'JavaScript', jsx: 'JavaScript (React)',
  python: 'Python', rust: 'Rust', go: 'Go', java: 'Java', kotlin: 'Kotlin',
  css: 'CSS', scss: 'SCSS', html: 'HTML', sql: 'SQL', graphql: 'GraphQL',
  json: 'JSON', yaml: 'YAML', bash: 'Shell', sh: 'Shell',
  markdown: 'Markdown', mermaid: 'Diagram', text: 'Text',
  svg: 'SVG', xml: 'XML', toml: 'TOML', r: 'R',
};

const FILE_ICONS: Record<string, string> = {
  typescript: '⚡', ts: '⚡', tsx: '⚛', javascript: '⚡', js: '⚡', jsx: '⚛',
  python: '🐍', rust: '🦀', go: '🔹', java: '☕', kotlin: '🟣',
  css: '🎨', scss: '🎨', html: '🌐', sql: '🗄️', json: '{ }',
  yaml: '⚙️', bash: '💻', sh: '💻', markdown: '📝',
  mermaid: '🔷', diagram: '🔷', text: '📄', svg: '🖼️', image: '🖼️',
};

const MIME_MAP: Record<string, string> = {
  json: 'application/json', html: 'text/html', css: 'text/css',
  sql: 'application/sql', csv: 'text/csv', markdown: 'text/markdown', md: 'text/markdown',
};
const EXT_MAP: Record<string, string> = {
  typescript: 'ts', javascript: 'js', python: 'py', rust: 'rs', go: 'go',
  java: 'java', kotlin: 'kt', css: 'css', scss: 'scss', html: 'html',
  sql: 'sql', json: 'json', yaml: 'yml', bash: 'sh', markdown: 'md',
  mermaid: 'mmd', text: 'txt', svg: 'svg',
};

const langLabel = (lang: string) => LANG_LABELS[lang?.toLowerCase()] ?? lang?.toUpperCase() ?? 'Code';
const fileIcon = (lang: string) => FILE_ICONS[lang?.toLowerCase()] ?? '📄';

function escapeHtml(s: string): string {
  return (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function downloadFile(content: string, filename: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ── PDF Export ────────────────────────────────────────────────────
async function exportAsPDF(content: string, title: string, language: string): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW  = doc.internal.pageSize.getWidth();
  const pageH  = doc.internal.pageSize.getHeight();
  const margin = 14;
  const usableW = pageW - margin * 2;

  doc.setFillColor(11, 15, 26);
  doc.rect(0, 0, pageW, 18, 'F');
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 12);
  doc.setTextColor(100, 120, 140);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(language.toUpperCase(), pageW - margin, 12, { align: 'right' });

  doc.setTextColor(40, 40, 40);
  doc.setFontSize(8.5);
  doc.setFont('courier', 'normal');
  const lines = doc.splitTextToSize(content, usableW);
  const lineH = 5;
  let y = 26;

  for (const line of lines) {
    if (y + lineH > pageH - margin) {
      doc.addPage();
      doc.setFillColor(11, 15, 26);
      doc.rect(0, 0, pageW, 10, 'F');
      doc.setTextColor(80, 100, 120);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.text(`${title} (cont.)`, margin, 7);
      doc.setTextColor(40, 40, 40);
      doc.setFontSize(8.5);
      doc.setFont('courier', 'normal');
      y = 16;
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  const pageCount = (doc.internal as any).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by Sedrex AI  •  Page ${i} of ${pageCount}`, pageW / 2, pageH - 6, { align: 'center' });
  }
  doc.save(`${title.replace(/[^a-z0-9_\-]/gi, '_')}.pdf`);
}

// ── DOCX Export ───────────────────────────────────────────────────
async function exportAsDOCX(content: string, title: string, language: string): Promise<void> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = await import('docx');
  const lines = content.split('\n');

  const wordDoc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: title, bold: true, size: 28 })],
        }),
        new Paragraph({
          children: [new TextRun({ text: `Language: ${language.toUpperCase()}   |   Generated by Sedrex AI`, italics: true, color: '888888', size: 18 })],
        }),
        new Paragraph({ children: [new TextRun({ text: '' })] }),
        ...lines.map(line =>
          new Paragraph({
            alignment: AlignmentType.LEFT,
            children: [new TextRun({ text: line.length > 0 ? line : ' ', font: 'Courier New', size: 18, color: '1a1a2e' })],
          })
        ),
      ],
    }],
  });

  const blob = await Packer.toBlob(wordDoc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-z0-9_\-]/gi, '_')}.docx`;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// ── Export Menu component ─────────────────────────────────────────
type ExportFormat = 'source' | 'pdf' | 'docx';

interface ExportMenuProps {
  artifact:  Artifact;
  content:   string;
  onExport:  (format: ExportFormat) => Promise<void>;
}

const ExportMenu: React.FC<ExportMenuProps> = ({ artifact, content, onExport }) => {
  const [open,      setOpen]      = useState(false);
  const [exporting, setExporting] = useState<ExportFormat | null>(null);
  const [dropPos,   setDropPos]   = useState({ top: 0, left: 0 });
  const btnRef  = useRef<HTMLButtonElement>(null);
  const dropRef = useRef<HTMLDivElement>(null);

  // Recompute portal position whenever menu opens
  useEffect(() => {
    if (!open || !btnRef.current) return;
    const rect = btnRef.current.getBoundingClientRect();
    const dropH = dropRef.current?.offsetHeight ?? 120;
    setDropPos({
      top:  Math.max(8, rect.top - dropH - 6),
      left: Math.max(8, rect.right - 170),
    });
  }, [open]);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const h = (e: MouseEvent) => {
      if (
        dropRef.current && !dropRef.current.contains(e.target as Node) &&
        btnRef.current  && !btnRef.current.contains(e.target as Node)
      ) setOpen(false);
    };
    const t = setTimeout(() => document.addEventListener('mousedown', h), 10);
    return () => { clearTimeout(t); document.removeEventListener('mousedown', h); };
  }, [open]);

  const handle = async (fmt: ExportFormat) => {
    setOpen(false);
    setExporting(fmt);
    try { await onExport(fmt); } finally { setExporting(null); }
  };

  const items: { id: ExportFormat; label: string; icon: string }[] = [
    { id: 'source', label: 'Source file',    icon: '📄' },
    { id: 'pdf',    label: 'Export as PDF',  icon: '📕' },
    { id: 'docx',   label: 'Export as DOCX', icon: '📘' },
  ];

  // Portal renders into document.body — escapes ap-code-viewer overflow:hidden
  const dropdown = open ? createPortal(
    <div ref={dropRef} style={{
      position: 'fixed', top: dropPos.top, left: dropPos.left,
      background: 'var(--bg-secondary, #0d1117)',
      border: '1px solid var(--border, rgba(255,255,255,0.12))',
      borderRadius: 10, boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
      minWidth: 170, zIndex: 99999, overflow: 'hidden',
    }}>
      {items.map(it => (
        <button key={it.id} onClick={() => handle(it.id)} style={{
          display: 'flex', alignItems: 'center', gap: 8,
          width: '100%', padding: '9px 14px', border: 'none',
          background: 'transparent', color: 'var(--text-primary)',
          cursor: 'pointer', fontSize: 13, textAlign: 'left',
        }}
          onMouseEnter={e => (e.currentTarget.style.background = 'rgba(16,185,129,0.08)')}
          onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
        >
          <span style={{ fontSize: 14 }}>{it.icon}</span>{it.label}
        </button>
      ))}
    </div>,
    document.body,
  ) : null;

  return (
    <>
      <button
        ref={btnRef}
        className="ap-action-btn"
        onClick={() => setOpen(v => !v)}
        disabled={!!exporting}
        title="Export"
      >
        {exporting
          ? <span className="ap-spinner" style={{ width: 10, height: 10 }} />
          : <Icons.Download className="icon-12" />}
        <span>{exporting ? 'Exporting…' : 'Export ▾'}</span>
      </button>
      {dropdown}
    </>
  );
};

type PanelTab = 'code' | 'preview' | 'history';

function isDiagramArtifact(a: Artifact): boolean {
  return a.type === 'diagram' || (a.language ?? '').toLowerCase() === 'mermaid';
}

// Every artifact has a preview — Python runs via Pyodide, JS executes, others display richly
function canPreviewArtifact(_a: Artifact): boolean { return true; }

// Handle raw base64 without data: prefix
function getImageSrc(content: string, title = ''): string {
  if (!content) return '';
  if (content.startsWith('data:') || content.startsWith('http')) return content;
  const ext = (title.split('.').pop() ?? 'png').toLowerCase();
  const mime = ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg'
    : ext === 'gif' ? 'image/gif'
      : ext === 'webp' ? 'image/webp'
        : ext === 'svg' ? 'image/svg+xml'
          : 'image/png';
  return `data:${mime};base64,${content}`;
}

// ── Universal srcdoc builder ──────────────────────────────────────
function buildSrcdoc(artifact: Artifact): string {
  let lang = (artifact.language ?? '').toLowerCase();
  const content = artifact.content ?? '';

  // ── Auto-detect React/JSX written with wrong fence tag ──────
  // AI often writes React code with ```javascript instead of ```jsx
  // Detect: has JSX element syntax AND React import/hooks → promote to jsx
  if (['javascript', 'js', 'typescript', 'ts'].includes(lang)) {
    const hasJSXTags = /<[A-Z][A-Za-z0-9]*[\s\/>]|<\/[A-Za-z][A-Za-z0-9]*>/.test(content);
    const hasReact = /import\s+.*[Rr]eact|from\s+['"]react['"]|useState|useEffect|useRef|React\./.test(content);
    const hasReturnJSX = /return\s*\(\s*<|=>\s*</.test(content);
    if ((hasJSXTags && hasReact) || hasReturnJSX) {
      lang = (lang === 'typescript' || lang === 'ts') ? 'tsx' : 'jsx';
    }
  }

  const base = `<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:system-ui,sans-serif;background:#0b0f1a;color:#e4e8f0;min-height:100vh}.sx-err{color:#f87171;background:rgba(248,113,113,.08);padding:14px;border-radius:8px;border:1px solid rgba(248,113,113,.25);font-family:monospace;font-size:13px;white-space:pre-wrap;margin:12px}.sx-out{font-family:'Fira Code',monospace;font-size:13px;line-height:1.6;padding:16px;white-space:pre-wrap;word-break:break-word}.sx-label{font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:rgba(16,185,129,.7);padding:12px 16px 4px;font-family:monospace}pre{margin:0}</style>`;

  // HTML direct — inject a compatibility patch for common AI-generated issues:
  // 1. Lucide deprecated icon names (twitter→x, etc.)
  // 2. Suppress CDN production warnings
  if (lang === 'html' || content.trimStart().toLowerCase().startsWith('<!doctype html') || content.trimStart().toLowerCase().startsWith('<html')) {
    const lucidePatch = `<script>
// Patch deprecated lucide icon names the AI commonly uses
document.addEventListener('DOMContentLoaded',()=>{
  const aliases={'twitter':'x','github':'github','linkedin':'linkedin','facebook':'facebook','instagram':'instagram','youtube':'youtube','mail':'mail','home':'house','search':'search'};
  const deprecated={'twitter':'x'};
  document.querySelectorAll('[data-lucide]').forEach(el=>{
    const name=el.getAttribute('data-lucide');
    if(deprecated[name])el.setAttribute('data-lucide',deprecated[name]);
  });
});
// Suppress CDN warnings from inside preview
const _cw=console.warn;console.warn=(...a)=>{if(typeof a[0]==='string'&&a[0].includes('cdn.tailwindcss.com'))return;_cw(...a);};
</script>`;
    // Inject before </head> if present, otherwise prepend
    if (content.includes('</head>')) return content.replace('</head>', lucidePatch + '</head>');
    return lucidePatch + content;
  }

  // SVG
  if (lang === 'svg' || content.trimStart().startsWith('<svg')) {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<style>body{display:flex;align-items:center;justify-content:center;padding:20px;background:#fff;min-height:100vh}</style></head><body>${content}</body></html>`;
  }

  // JSX/TSX — Babel (FIXED: was crashing all React previews due to duplicate const Root=)
  if (lang === 'jsx' || lang === 'tsx') {
    // ── Extract default export name ───────────────────────────────
    // Babel wraps all code in an IIFE so `const Foo = () => ...` never
    // reaches window. We capture the export name here and register it
    // to window INSIDE the Babel script (same IIFE scope).
    // Handle both `export default Name` and `export default function Name()`
    const _exportMatch = content.match(/export\s+default\s+(?:function\s+|class\s+)?(\w+)/);
    // Reject JS keywords that can't be component names
    const _jsKeywords = new Set(['function','class','const','let','var','async','abstract']);
    const _exportedName = (_exportMatch && !_jsKeywords.has(_exportMatch[1])) ? _exportMatch[1] : null;

    // ── Shims as TS string vars ───────────────────────────────────
    // Embedding complex JS directly inside a template literal causes
    // Babel to throw "Missing semicolon" when parsing ArtifactPanel.tsx.
    // Building them as plain TS string concatenation avoids this.
    const _framerShim = '(function(){'
      + 'var M=window.Motion||window.FramerMotion||{};'
      + 'var keys=["motion","AnimatePresence","useAnimation","useMotionValue",'
      + '"useTransform","useSpring","useCycle","useInView","useScroll",'
      + '"useVelocity","useReducedMotion","animate","stagger",'
      + '"MotionConfig","LazyMotion","domAnimation","useMotionValueEvent"];'
      + 'keys.forEach(function(n){if(M[n]!==undefined)window[n]=M[n];});'
      + 'if(!window.motion){'
      + 'function _m(tag){return function(p){'
      + 'var q={};Object.keys(p||{}).forEach(function(k){'
      + 'if(!/^(initial|animate|exit|transition|variants|whileHover|whileTap|'
      + 'whileFocus|whileInView|layout|layoutId|drag|dragConstraints|viewport|'
      + 'onAnimationStart|onAnimationComplete)$/.test(k))q[k]=p[k];});'
      + 'return React.createElement(tag,q,p&&p.children);};};'
      + 'var mo={};'
      + '["div","span","section","article","header","footer","main",'
      + '"nav","aside","ul","li","ol","p","h1","h2","h3","h4",'
      + '"h5","h6","a","button","img","form","input","label",'
      + '"svg","path","circle","rect","g"].forEach(function(t){mo[t]=_m(t);});'
      + 'window.motion=mo;}'
      + 'if(!window.AnimatePresence)window.AnimatePresence=function(p){return p&&p.children||null;};'
      + 'if(!window.useAnimation)window.useAnimation=function(){return{start:function(){},stop:function(){}};};'
      + 'if(!window.useMotionValue)window.useMotionValue=function(v){return{get:function(){return v;},set:function(){}};};'
      + 'if(!window.useScroll)window.useScroll=function(){return{scrollY:{get:function(){return 0;},onChange:function(){}},scrollYProgress:{get:function(){return 0;}}};};'
      + 'if(!window.useInView)window.useInView=function(){return[null,true];};'
      + 'if(!window.useTransform)window.useTransform=function(v,i,o){return{get:function(){return o[0];}};};'
      + '})();';

    // lucide UMD exposes icons as direct PascalCase keys on window.lucide
    // (NOT on window.lucide.icons which doesn't exist in current builds)
    // lucide shim: 3-tier approach
    // Tier 1: lucide-react UMD (window.LucideReact) — ready-made React components
    // Tier 2: vanilla lucide UMD (window.lucide) — reconstruct from SVG data
    // Tier 3: stub fallback — generic SVG box for any icon not found
    const _lucideShim = '(function(){'
      + 'function _icon(sz,cl,sw,cm,children){'
      + 'return React.createElement("svg",{'
      + 'xmlns:"http://www.w3.org/2000/svg",width:sz,height:sz,'
      + 'viewBox:"0 0 24 24",fill:"none",stroke:cl,'
      + 'strokeWidth:sw,strokeLinecap:"round",strokeLinejoin:"round",className:cm'
      + '},children);}'
      + 'function _mkIcon(children){'
      + 'return function(props){'
      + 'var sz=(props&&props.size)||24,cl=(props&&props.color)||"currentColor",'
      + 'sw=(props&&props.strokeWidth)||2,cm=(props&&props.className)||"";'
      + 'return _icon(sz,cl,sw,cm,children);};}'
      // Tier 1: lucide-react UMD exposes React components directly
      + 'var LR=window.LucideReact||{};'
      + 'Object.keys(LR).forEach(function(n){'
      + 'if(/^[A-Z]/.test(n)&&typeof LR[n]==="function"&&!window[n])window[n]=LR[n];});'
      // Tier 2: vanilla lucide UMD — data arrays → React SVG components
      + 'var LL=window.lucide||{};'
      + 'if(LL.icons){Object.keys(LL.icons).forEach(function(k){'
      + 'var PK=k.split("-").map(function(p){return p[0].toUpperCase()+p.slice(1);}).join("");'
      + 'if(window[PK])return;'
      + 'var d=LL.icons[k];'
      + 'if(Array.isArray(d))window[PK]=_mkIcon(d.map(function(c,i){return React.createElement(c[0],Object.assign({key:i},c[1]||{}));}));'
      + '});}'
      // Tier 3: stub fallback for 80+ common icon names not yet defined
      + 'var _stub=_mkIcon([React.createElement("rect",{x:3,y:3,width:18,height:18,rx:2})]);'
      + '["ShoppingBag","ShoppingCart","Menu","X","ArrowRight","ArrowLeft","ArrowUp","ArrowDown",'
      + '"Instagram","Twitter","Facebook","Github","Youtube","Linkedin",'
      + '"ChevronRight","ChevronLeft","ChevronDown","ChevronUp",'
      + '"Search","User","Users","Heart","Star","Home","Settings","Bell",'
      + '"Plus","Minus","Check","Edit","Trash","Trash2","Download","Upload",'
      + '"Share","Share2","Copy","Mail","Phone","MapPin","Map","Calendar",'
      + '"Clock","Tag","Filter","Grid","List","Eye","EyeOff","Lock","Unlock",'
      + '"Info","AlertCircle","XCircle","CheckCircle","AlertTriangle",'
      + '"Loader","Loader2","RefreshCw","RotateCw","ZoomIn","ZoomOut",'
      + '"Maximize","Minimize","Moon","Sun","Wifi","Battery","Bluetooth",'
      + '"Camera","Image","Video","Music","Play","Pause","Square",'
      + '"Volume","Volume2","VolumeX","Mic","MicOff","Send","MessageCircle",'
      + '"Globe","Link","ExternalLink","Bookmark","Flag","Award","Gift",'
      + '"Package","Box","Layers","Layout","Sidebar","Columns",'
      + '"BarChart","BarChart2","LineChart","PieChart","TrendingUp","TrendingDown",'
      + '"DollarSign","CreditCard","Wallet","Percent","Hash","AtSign",'
      + '"Code","Code2","Terminal","Database","Server","Cloud","Cpu","Monitor",'
      + '"Smartphone","Tablet","Laptop","Printer","Headphones","Speaker","Zap",'
      + '"Activity","Target","Anchor","Aperture","Archive","Book","Briefcase",'
      + '"Compass","Crop","Disc","Feather","Folder","FolderOpen","HelpCircle",'
      + '"Key","Layers","Leaf","LogIn","LogOut","Navigation","Paperclip",'
      + '"Power","Radio","Save","Scissors","Shield","ShieldCheck","Sliders",'
      + '"Smile","Sunset","Sunrise","Thermometer","ToggleLeft","ToggleRight",'
      + '"Tool","Truck","Umbrella","Watch","Wind","XSquare","CheckSquare",'
      + '"Circle","Triangle","Hexagon","Octagon","Pentagon"].forEach(function(n){'
      + 'if(!window[n])window[n]=_stub;});'
      + '})();'

    // ── Strip imports/exports for browser execution ───────────────
    const clean = content
      .replace(/^export\s+default\s+(\w+)\s*;?\s*$/gm, '/* exported: $1 */')
      .replace(/^export\s+default\s+/gm, '')
      .replace(/^export\s+(const|let|var|function|class)\s+/gm, '$1 ')
      .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
      // FIX: strip multiline imports — old /.* regex misses framer-motion,
      // lucide-react etc which span multiple lines
      .replace(/import\s+(?:type\s+)?\{[\s\S]*?\}\s*from\s*['"][^'"]+['"]\s*;?/g, '')
      .replace(/import\s+\*\s+as\s+\w+\s+from\s*['"][^'"]+['"]\s*;?/g, '')
      .replace(/import\s+\w+\s*,\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"]\s*;?/g, '')
      .replace(/import\s+\w+\s+from\s*['"][^'"]+['"]\s*;?/g, '')
      .replace(/import\s+['"][^'"]+['"]\s*;?/g, '');

    // ── rootFinderScript ──────────────────────────────────────────
    // Runs AFTER Babel compiles the user code.
    // Priority: window.__sx_default (registered from IIFE) first,
    // then well-known names, then any uppercase function returning JSX.
    const rootFinderScript = `
(function(){
  // window.__sx_default: set from inside Babel IIFE right after user code.
  // This is the most reliable registration — in the same scope as the component.
  var _Root = window.__sx_default || null;

  // Fallback: scan only well-known component names (NO generic window scan —
  // that was accidentally picking up Tailwind/lucide/framer CDN functions).
  if (!_Root) {
    var _pref=['App','Component','Counter','Dashboard','Page','Main','Home',
      'Index','Root','Portfolio','Landing','Layout','Screen','View','Widget',
      'Hero','Profile','Showcase','Form','Modal','Card','Table','Grid','Chart'];
    for(var _i=0;_i<_pref.length;_i++){
      var _c=window[_pref[_i]];
      if(typeof _c==='function'&&!_c.toString().includes('[native code]')){
        _Root=_c;break;
      }
    }
  }

  var _el=document.getElementById('root');
  if(_Root){
    try{
      ReactDOM.createRoot(_el).render(React.createElement(_Root));
    }catch(e){
      _el.innerHTML='<div class="sx-err">Render error: '+e.message+'</div>';
    }
  }else{
    _el.innerHTML='<div class="sx-err" style="padding:20px;font-family:monospace">'
      +'<strong>No component found to render.</strong><br/><br/>'
      +'Sedrex looked for: <em>App, Component, Counter, Dashboard, Page</em> and more.<br/><br/>'
      +'Make sure your component has a capital letter name and uses: <code>export default YourName</code></div>';
  }
})();`

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<base target="_blank"/>
<script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
<script>
try{localStorage.setItem('_sx','1');localStorage.removeItem('_sx');}
catch(e){Object.defineProperty(window,'localStorage',{value:{_d:{},setItem(k,v){this._d[k]=v},getItem(k){return this._d[k]??null},removeItem(k){delete this._d[k]},clear(){this._d={}}}});}
</script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/framer-motion@11/dist/framer-motion.js"></script>
<script src="https://unpkg.com/lucide-react/dist/umd/lucide-react.min.js"></script>
<script>
const _cw=console.warn;console.warn=(...a)=>{if(typeof a[0]==='string'&&(a[0].includes('cdn.tailwindcss.com')||a[0].includes('should not be used in production')))return;_cw(...a);};
</script>
<script>${_framerShim}</script>
<script>${_lucideShim}</script>
${base}
<style>
body{padding:0;margin:0}
.sx-loading{display:flex;align-items:center;justify-content:center;height:80px;color:rgba(16,185,129,.7);font-family:monospace;font-size:13px;gap:8px}
</style>
</head>
<body>
<div id="root"><div class="sx-loading">⚡ Rendering…</div></div>
<script>
window.onerror=function(msg,src,line,col,err){
  document.getElementById('root').innerHTML=
    '<div class="sx-err"><strong>Runtime Error</strong><br/>'+msg+
    (err&&err.stack?'<br/><small style="opacity:.6">'+err.stack.split('\\n').slice(0,3).join('<br/>')+'</small>':'')+'</div>';
  return true;
};
window.addEventListener('unhandledrejection',function(e){
  document.getElementById('root').innerHTML=
    '<div class="sx-err"><strong>Unhandled Promise</strong><br/>'+(e.reason?.message||String(e.reason))+'</div>';
});
</script>
<script type="text/babel" data-presets="react,typescript">
try {
  const {
    useState, useEffect, useRef, useCallback, useMemo,
    useReducer, useContext, createContext, Fragment, memo,
    forwardRef, useImperativeHandle, useLayoutEffect,
    useDebugValue, useId, useTransition, useDeferredValue,
  } = React;

  ${clean}

  // Register the default export to window so rootFinderScript can find it.
  // Babel wraps all code in an IIFE — const/let vars don't reach window.
  // This line executes in the SAME IIFE scope, so it CAN access the component.
  ${_exportedName ? `try{window.__sx_default=${_exportedName};}catch(_e){}` : ''}

} catch(compileErr) {
  document.getElementById('root').innerHTML=
    '<div class="sx-err"><strong>Compile Error</strong><br/>'+compileErr.message+'</div>';
}
</script>
<script>
${rootFinderScript}
</script>
</body>
</html>`;
  }

  // JavaScript / TypeScript — console output sandbox
  if (['javascript', 'js', 'typescript', 'ts'].includes(lang)) {
    const isTS = lang === 'typescript' || lang === 'ts';
    // Strip TypeScript-only syntax for browser eval
    const jsCode = isTS
      ? content
          .replace(/^import\s+type\s+.*$/gm, '')
          .replace(/^import\s+.*from\s+['"][^'"]+['"]\s*;?$/gm, '')
          .replace(/^export\s+default\s+/gm, 'window._defaultExport = ')
          .replace(/^export\s+/gm, '')
          .replace(/:\s*(string|number|boolean|void|any|unknown|never|object|null|undefined|bigint)(\[\]|\s*\|\s*null|\s*\|\s*undefined)*/g, '')
          .replace(/^(interface|type)\s+\w[^{]*\{[\s\S]*?\n\}/gm, '')
          .replace(/<[A-Z][A-Za-z0-9]*(?:\s*,\s*[A-Z][A-Za-z0-9]*)*>/g, '')
          .replace(/as\s+\w[\w.<>|&\[\]]*(?=[\s;,)\]])/g, '')
      : content
          .replace(/^import\s+.*from\s+['"][^'"]+['"]\s*;?$/gm, '')
          .replace(/^export\s+default\s+/gm, 'window._defaultExport = ')
          .replace(/^export\s+/gm, '');
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}</head><body><div class="sx-label">${lang === 'typescript' || lang === 'ts' ? 'TypeScript' : 'JavaScript'} Output</div><div class="sx-out" id="out"></div><script>const _out=document.getElementById('out');const _w=(type,...a)=>{const d=document.createElement('div');d.style.color=type==='error'?'#f87171':type==='warn'?'#fbbf24':'#e4e8f0';d.textContent=a.map(x=>typeof x==='object'?JSON.stringify(x,null,2):String(x)).join(' ');_out.appendChild(d);};const console={log:(...a)=>_w('log',...a),error:(...a)=>_w('error',...a),warn:(...a)=>_w('warn',...a),info:(...a)=>_w('log',...a),table:(d)=>_w('log',JSON.stringify(d,null,2)),dir:(d)=>_w('log',JSON.stringify(d,null,2))};window.onerror=function(m,s,l,c,e){_w('error','Error: '+m+(e&&e.stack?'\\n'+e.stack.split('\\n').slice(0,3).join('\\n'):''));return true;};try{${jsCode}}catch(e){_w('error',e.message+(e.stack?'\\n'+e.stack.split('\\n').slice(0,4).join('\\n'):''));}if(!_out.children.length){const d=document.createElement('div');d.style.color='rgba(255,255,255,.3)';d.style.fontStyle='italic';d.textContent='No console output';_out.appendChild(d);}</script></body></html>`;
  }

  // Python — Pyodide
  if (lang === 'python' || lang === 'py') {
    // safeCode: user code JSON-serialized → safe to inject as JS string literal
    const safeCode = JSON.stringify(content);

    // Python wrapper: redirects stdout via __captured__ list (works on ALL Pyodide versions)
    // Defined as TS string concatenation — NO backticks → no outer template literal conflict
    const _pyWrapStr = 'import sys,io\n'
      + 'class _Cap(io.StringIO):\n'
      + '    def write(self,s):\n'
      + '        __captured__.append(s)\n'
      + '        return len(s)\n'
      + 'sys.stdout=_Cap();sys.stderr=_Cap()\n'
      + 'try:\n'
      + '    exec(_sx_src)\n'
      + 'except Exception:\n'
      + '    import traceback\n'
      + '    __captured__.append(traceback.format_exc())\n';
    // JSON.stringify → double-quoted JS string literal, safe inside HTML <script>
    const safeWrap = JSON.stringify(_pyWrapStr);

    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<script src="https://cdn.jsdelivr.net/pyodide/v0.26.2/full/pyodide.js"></script></head><body><div class="sx-label">Python Output</div><div class="sx-out" id="out"><span style="color:rgba(16,185,129,.7)">Loading Python runtime (first run ~5s)…</span></div><script>(async()=>{const out=document.getElementById('out');try{const pyodide=await loadPyodide();pyodide.globals.set('__captured__',[]);pyodide.globals.set('_sx_src',${safeCode});await pyodide.runPythonAsync(${safeWrap});const _raw=pyodide.globals.get('__captured__');const lines=(_raw&&typeof _raw.toJs==='function')?Array.from(_raw.toJs()):Array.from(_raw||[]);const result=lines.join('');out.innerHTML='';if(result.trim()){result.split('\n').forEach(function(line){const d=document.createElement('div');const isErr=line.includes('Error:')||line.startsWith('Traceback')||line.startsWith('  File');d.style.color=isErr?'#f87171':'#e4e8f0';d.textContent=line;out.appendChild(d);});}else{out.innerHTML='<span style="color:rgba(255,255,255,.3);font-style:italic">No output</span>';}}catch(e){out.innerHTML='<div class="sx-err"><strong>Error</strong><br/>'+e.message+'</div>';}})();</script></body></html>`;
  }

  // CSS live preview
  if (lang === 'css' || lang === 'scss') {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{box-sizing:border-box}body{font-family:system-ui,sans-serif;background:#fff;color:#111;padding:20px;line-height:1.5}</style><style>${content}</style></head><body><h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3><p>Paragraph with <a href="#">a link</a>, <strong>bold</strong>, <em>italic</em>.</p><button class="btn" type="button">Button</button><button class="btn btn-primary" type="button">Primary</button><ul><li>List item one</li><li>List item two</li><li>List item three</li></ul><div class="card"><div class="card-header">Card Header</div><div class="card-body">Card body content.</div></div><input class="input form-control" type="text" placeholder="Input field" style="margin:8px 0;display:block"/><div class="alert alert-success" style="margin-top:8px">Success alert</div><div class="alert alert-danger alert-error" style="margin-top:4px">Error alert</div><div style="display:flex;gap:8px;margin-top:12px;flex-wrap:wrap"><span class="badge badge-primary">Badge</span><span class="tag">Tag</span><span class="chip">Chip</span></div><table class="table" style="margin-top:12px;width:100%"><thead><tr><th>Name</th><th>Role</th><th>Status</th></tr></thead><tbody><tr><td>Alice</td><td>Admin</td><td>Active</td></tr><tr><td>Bob</td><td>User</td><td>Inactive</td></tr></tbody></table></body></html>`;
  }

  // JSON tree
  if (lang === 'json') {
    const js = JSON.stringify(content);
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<style>body{padding:16px}.jv{font-family:'Fira Code',monospace;font-size:13px;line-height:1.7}.jk{color:#818cf8}.jn{color:#79c0ff}.js{color:#98c379}.jb{color:#f472b6}details>summary{cursor:pointer;list-style:none;outline:none;user-select:none}details>summary::-webkit-details-marker{display:none}</style></head><body><div class="jv" id="root"></div><script>function r(v,d=0){if(v===null)return '<span class="jb">null</span>';if(typeof v==='boolean')return '<span class="jb">'+v+'</span>';if(typeof v==='number')return '<span class="jn">'+v+'</span>';if(typeof v==='string')return '<span class="js">"'+v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')+'</span>';if(Array.isArray(v)){if(!v.length)return '<span style="color:#94a3b8">[]</span>';return '<details open><summary><span style="color:#94a3b8">[ '+v.length+' items ]</span></summary>'+v.map((x,i)=>'<div style="padding-left:18px">'+r(x,d+1)+(i<v.length-1?',':'')+'</div>').join('')+'</details>';}if(typeof v==='object'){const ks=Object.keys(v);if(!ks.length)return '<span style="color:#94a3b8">{}</span>';return '<details open><summary><span style="color:#94a3b8">{ '+ks.length+' keys }</span></summary>'+ks.map((k,i)=>'<div style="padding-left:18px"><span class="jk">"'+k+'"</span>: '+r(v[k],d+1)+(i<ks.length-1?',':'')+'</div>').join('')+'</details>';}return String(v);}try{document.getElementById('root').innerHTML=r(JSON.parse(${js}));}catch(e){document.getElementById('root').innerHTML='<div class="sx-err">JSON Parse Error: '+e.message+'</div>';}</script></body></html>`;
  }

  // Markdown
  if (lang === 'markdown' || lang === 'md') {
    const ms = JSON.stringify(content);
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/github-markdown-css/github-markdown-dark.min.css"><style>body{background:#0b0f1a;padding:24px;max-width:800px;margin:0 auto}.markdown-body{background:transparent;color:#e4e8f0;font-family:system-ui,sans-serif}</style></head><body class="markdown-body"><div id="md"></div><script>document.getElementById('md').innerHTML=marked.parse(${ms});</script></body></html>`;
  }

  // SQL display
  if (lang === 'sql') {
    const ss = JSON.stringify(content);
    const kk = JSON.stringify(['SELECT', 'FROM', 'WHERE', 'JOIN', 'LEFT', 'RIGHT', 'INNER', 'OUTER', 'FULL', 'ON', 'GROUP', 'ORDER', 'BY', 'HAVING', 'LIMIT', 'OFFSET', 'INSERT', 'INTO', 'VALUES', 'UPDATE', 'SET', 'DELETE', 'CREATE', 'TABLE', 'ALTER', 'DROP', 'INDEX', 'VIEW', 'WITH', 'AS', 'AND', 'OR', 'NOT', 'IN', 'LIKE', 'ILIKE', 'BETWEEN', 'IS', 'NULL', 'DISTINCT', 'COUNT', 'SUM', 'AVG', 'MAX', 'MIN', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'BEGIN', 'COMMIT', 'ROLLBACK', 'RETURNING', 'PRIMARY', 'KEY', 'FOREIGN', 'REFERENCES', 'UNIQUE', 'DEFAULT', 'CONSTRAINT', 'IF', 'EXISTS']);
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<style>body{padding:16px}.note{color:rgba(16,185,129,.7);font-size:11px;margin-bottom:10px;font-family:monospace}pre{background:#0d1117;border:1px solid rgba(255,255,255,.08);border-radius:8px;padding:20px;font-family:'Fira Code',monospace;font-size:13px;line-height:1.65;overflow:auto;color:#e4e8f0}.kw{color:#c9a84c;font-weight:700}.str{color:#98c379}.cmt{color:#6b7280;font-style:italic}.num{color:#79c0ff}</style></head><body><div class="note">📝 SQL — syntax display only (no database connection)</div><pre id="sql"></pre><script>const sql=${ss};const kws=${kk};let h=sql.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');h=h.replace(/'[^']*'/g,m=>'<span class="str">'+m+'</span>');h=h.replace(/--[^\\n]*/g,m=>'<span class="cmt">'+m+'</span>');h=h.replace(/\\b(\\d+(\\.\\d+)?)\\b/g,'<span class="num">$1</span>');const re=new RegExp('\\\\b('+kws.join('|')+')\\\\b','gi');h=h.replace(re,m=>'<span class="kw">'+m.toUpperCase()+'</span>');document.getElementById('sql').innerHTML=h;</script></body></html>`;
  }

  // Bash/Shell
  if (lang === 'bash' || lang === 'sh' || lang === 'shell') {
    const ls = JSON.stringify(content.split('\n'));
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<style>body{padding:0;background:#0d1117}.terminal{background:#0d1117;border:1px solid rgba(255,255,255,.08);border-radius:8px;margin:16px;overflow:hidden}.term-bar{background:#1c1c1c;padding:10px 16px;display:flex;gap:6px;align-items:center}.dot{width:12px;height:12px;border-radius:50%}.term-body{padding:16px;font-family:'Fira Code',monospace;font-size:13px;line-height:1.7}.prompt{color:#c9a84c}.cmd{color:#e4e8f0}.cmt{color:#6b7280;font-style:italic}.note{color:rgba(255,255,255,.3);font-size:11px;margin-top:12px;padding-top:12px;border-top:1px solid rgba(255,255,255,.06)}</style></head><body><div class="terminal"><div class="term-bar"><div class="dot" style="background:#ef4444"></div><div class="dot" style="background:#f59e0b"></div><div class="dot" style="background:#c9a84c"></div></div><div class="term-body" id="out"></div></div><script>const lines=${ls};const out=document.getElementById('out');lines.forEach(line=>{const d=document.createElement('div');if(!line.trim()){d.innerHTML='&nbsp;';out.appendChild(d);return;}if(line.trim().startsWith('#')){d.innerHTML='<span class="cmt">'+line.replace(/</g,'&lt;')+'</span>';}else{d.innerHTML='<span class="prompt">$ </span><span class="cmd">'+line.replace(/</g,'&lt;').replace(/>/g,'&gt;')+'</span>';}out.appendChild(d);});const n=document.createElement('div');n.className='note';n.textContent='Shell preview is read-only. Run in your terminal to execute.';out.appendChild(n);</script></body></html>`;
  }

  // Generic fallback — all other languages (Go, Rust, Java, C, C++, Ruby, PHP, Swift, etc.)
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">${base}<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css"><script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script><style>body{padding:16px;background:#0b0f1a}pre{margin:0;border-radius:8px;overflow:auto;background:#0d1117!important}pre code.hljs{padding:20px;font-size:13px;line-height:1.65;border-radius:8px}.badge{display:inline-block;background:rgba(16,185,129,.1);color:#c9a84c;font-family:monospace;font-size:10px;padding:2px 8px;border-radius:4px;margin-bottom:10px;text-transform:uppercase;font-weight:700}</style></head><body><div class="badge">${escapeHtml(lang || 'code')}</div><pre><code class="language-${escapeHtml(lang || 'plaintext')}">${escapeHtml(content)}</code></pre><script>hljs.highlightAll();</script></body></html>`;
}

// ── Diagram Viewer ────────────────────────────────────────────────
// FIX: Loads mermaid content if empty before rendering
const DiagramViewer = memo(({ artifact }: { artifact: Artifact }) => {
  const [svg, setSvg] = useState('');
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [fullContent, setFullContent] = useState(artifact.content ?? '');
  const [fetching, setFetching] = useState(false);

  useEffect(() => {
    const c = artifact.content ?? '';
    if (c.trim() === '') {
      setFetching(true);
      loadArtifactContent(artifact.id).then(fetched => {
        setFullContent(fetched);
        setFetching(false);
      }).catch(() => setFetching(false));
    } else {
      setFullContent(c);
    }
  }, [artifact.id, artifact.content]);

  useEffect(() => {
    if (fetching || !fullContent.trim()) return;
    let cancelled = false;
    (async () => {
      try {
        const mermaid = (await import('mermaid')).default;
        // securityLevel: 'antiscript' — keeps all SVG structure intact while
        // stripping event handlers. 'loose' forces htmlLabels ON regardless of
        // the flowchart setting, causing <foreignObject> nodes that DOMPurify's
        // svg profile strips → blank labels.
        // htmlLabels: false → native SVG <text> elements, always preserved.
        mermaid.initialize({
          startOnLoad: false,
          theme: 'dark',
          securityLevel: 'antiscript',
          maxTextSize: 500000,
          flowchart: {
            htmlLabels: false,
            useMaxWidth: true,
            rankSpacing: 50,
            nodeSpacing: 30,
          },
          maxEdges: 500,
        });
        const id = 'ap-' + Math.random().toString(36).slice(2, 9);
        const sanitized = fullContent
          .split('\n')
          .filter((line: string) => !line.trim().startsWith('//') && !line.trim().startsWith('#'))
          .join('\n')
          .replace(/^[\w./\-]+\.mmd\s*\n/m, '')
          .trim();
        const { svg: rendered } = await mermaid.render(id, sanitized);
        if (!cancelled) setSvg(rendered);
      } catch (e: any) {
        if (!cancelled) setError(e.message || 'Invalid diagram syntax');
      }
    })();
    return () => { cancelled = true; };
  }, [fullContent, fetching]);

  const handleCopy = async () => {
    try { await navigator.clipboard.writeText(fullContent); } catch { }
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="ap-code-viewer">
      <div className="ap-code-toolbar">
        <div className="ap-code-meta">
          <span className="ap-code-icon">🔷</span>
          <span className="ap-code-lang">Mermaid Diagram</span>
          <span className="ap-code-lines">{artifact.lineCount} lines</span>
        </div>
        <div className="ap-code-actions">
          {svg && <button className="ap-action-btn" onClick={() => downloadFile(svg, `${artifact.title}.svg`, 'image/svg+xml')}><Icons.Download className="icon-12" /><span>SVG</span></button>}
          <button className="ap-action-btn" onClick={() => downloadFile(fullContent, `${artifact.title}.mmd`, 'text/plain')}><Icons.Download className="icon-12" /><span>Source</span></button>
          <button className={`ap-action-btn${copied ? ' ap-action-btn--success' : ''}`} onClick={handleCopy}>{copied ? <Icons.Check className="icon-12" /> : <Icons.Copy className="icon-12" />}<span>{copied ? 'Copied!' : 'Copy'}</span></button>
        </div>
      </div>
      {error ? (
        <div style={{ padding: 20 }}><div style={{ color: '#f87171', marginBottom: 12, fontSize: 13 }}>⚠ {error}</div><pre style={{ fontSize: 11, opacity: 0.6, overflowX: 'auto', color: 'var(--text-secondary)' }}>{fullContent}</pre></div>
      ) : svg ? (
        <div className="ap-code-scroll" style={{ padding: 20, display: 'flex', justifyContent: 'center' }}><div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(svg, { USE_PROFILES: { svg: true, svgFilters: true } }) }} style={{ maxWidth: '100%' }} /></div>
      ) : (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 200 }}><div className="ap-spinner" /></div>
      )}
    </div>
  );
});

// ── Code Viewer ───────────────────────────────────────────────────
// FIX: Detects empty content (metadataOnly) and fetches before highlighting
const CodeViewer = memo(({ artifact, onSwitchToPreview }: { artifact: Artifact; onSwitchToPreview?: () => void }) => {
  const [copied, setCopied] = useState(false);
  const [highlighted, setHighlighted] = useState('');
  const [fullContent, setFullContent] = useState(artifact.content ?? '');
  const [fetching, setFetching] = useState(false);

  // Fetch content if empty
  useEffect(() => {
    const c = artifact.content ?? '';
    if (c.trim() === '') {
      setFetching(true);
      loadArtifactContent(artifact.id).then(fetched => {
        setFullContent(fetched);
        setFetching(false);
      }).catch(() => { setFetching(false); });
    } else {
      setFullContent(c);
    }
  }, [artifact.id, artifact.content]);

  useEffect(() => {
    if (fetching) return;
    let cancelled = false;
    (async () => {
      try {
        const hljs = (await import('highlight.js')).default;
        const lang = (artifact.language ?? '').toLowerCase();
        const res = lang && hljs.getLanguage(lang) ? hljs.highlight(fullContent, { language: lang, ignoreIllegals: true }).value : hljs.highlightAuto(fullContent).value;
        if (!cancelled) setHighlighted(res);
      } catch { if (!cancelled) setHighlighted(escapeHtml(fullContent)); }
    })();
    return () => { cancelled = true; };
  }, [fullContent, fetching, artifact.language]);

  const handleCopy = useCallback(async () => {
    try { await navigator.clipboard.writeText(fullContent); }
    catch { const ta = document.createElement('textarea'); ta.value = fullContent; ta.style.cssText = 'position:fixed;opacity:0'; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); document.body.removeChild(ta); }
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  }, [fullContent]);

  const handleDownload = useCallback(() => {
    const lang = (artifact.language ?? '').toLowerCase();
    const ext = EXT_MAP[lang] || lang || 'txt';
    const mime = MIME_MAP[lang] || 'text/plain';
    const filename = artifact.filePath ? artifact.filePath.split('/').pop()! : `${artifact.title.replace(/[^a-z0-9]/gi, '_')}.${ext}`;
    downloadFile(fullContent, filename, mime);
  }, [artifact, fullContent]);

  const handleExport = useCallback(async (format: ExportFormat) => {
    const lang = (artifact.language ?? '').toLowerCase();
    const ext  = EXT_MAP[lang] || lang || 'txt';
    const mime = MIME_MAP[lang] || 'text/plain';
    switch (format) {
      case 'source': {
        const filename = artifact.filePath
          ? artifact.filePath.split('/').pop()!
          : `${artifact.title.replace(/[^a-z0-9]/gi, '_')}.${ext}`;
        downloadFile(fullContent, filename, mime);
        break;
      }
      case 'pdf':  await exportAsPDF(fullContent, artifact.title, lang); break;
      case 'docx': await exportAsDOCX(fullContent, artifact.title, lang); break;
    }
  }, [artifact, fullContent]);

  const isRunnable = ['javascript', 'js', 'typescript', 'ts', 'jsx', 'tsx',
    'python', 'py', 'html', 'css', 'json'].includes((artifact.language ?? '').toLowerCase());

  return (
    <div className="ap-code-viewer">
      <div className="ap-code-toolbar">
        <div className="ap-code-meta">
          <span className="ap-code-icon">{fileIcon(artifact.language)}</span>
          <span className="ap-code-lang">{langLabel(artifact.language)}</span>
          {artifact.filePath && <span className="ap-code-path">{artifact.filePath}</span>}
          <span className="ap-code-lines">{artifact.lineCount} lines</span>
        </div>
        <div className="ap-code-actions">
          {isRunnable && onSwitchToPreview && (
            <button className="ap-action-btn" onClick={onSwitchToPreview} title="Run" style={{ color: 'var(--accent, #10B981)' }}>
              <svg viewBox="0 0 12 12" width="10" height="10" fill="currentColor"><polygon points="2,1 11,6 2,11" /></svg>
              <span>Run ▶</span>
            </button>
          )}
          <ExportMenu artifact={artifact} content={fullContent} onExport={handleExport} />
          <button className={`ap-action-btn${copied ? ' ap-action-btn--success' : ''}`} onClick={handleCopy}>{copied ? <Icons.Check className="icon-12" /> : <Icons.Copy className="icon-12" />}<span>{copied ? 'Copied!' : 'Copy'}</span></button>
        </div>
      </div>
      {/* CSS import warning — shown when a React/JS artifact imports a CSS file.
          The preview sandbox strips all CSS imports so styles from those files
          never apply. Alert the user so they know why things look unstyled. */}
      {!fetching && /^\s*import\s+['"][^'"]+\.css['"]\s*;?/m.test(fullContent) && (
        <div style={{
          display: 'flex', alignItems: 'flex-start', gap: 10,
          margin: '12px 16px 0', padding: '10px 14px',
          background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.35)',
          borderRadius: 8, fontSize: 12, color: '#facc15', lineHeight: 1.5,
        }}>
          <span style={{ fontSize: 15, flexShrink: 0 }}>⚠</span>
          <span>
            <strong>CSS imports are not supported in the preview.</strong>
            {' '}External stylesheet imports are stripped when the sandbox runs.
            Use <code style={{ background: 'rgba(255,255,255,0.08)', padding: '1px 4px', borderRadius: 3 }}>style={'{{}}'}</code> inline objects
            or a <code style={{ background: 'rgba(255,255,255,0.08)', padding: '1px 4px', borderRadius: 3 }}>&lt;style&gt;</code> tag inside your component instead.
          </span>
        </div>
      )}
      {fetching ? (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 200 }}>
          <div className="ap-spinner" />
        </div>
      ) : (
        <div className="ap-code-scroll"><pre className="ap-code-pre"><code className={`hljs language-${artifact.language}`} dangerouslySetInnerHTML={{ __html: highlighted || escapeHtml(fullContent) }} /></pre></div>
      )}
    </div>
  );
});

// ── Preview Pane — universal, always renders ──────────────────────
// FIX: Detects empty content (metadataOnly load) and fetches full
// content before rendering. Shows spinner during fetch.

// ── Lucide icon name fixer ────────────────────────────────────────
// Some icon names changed between lucide versions. Fix known renames
// and pin unpkg to a stable version to avoid future breakage.
function fixLucideIcons(html: string): string {
  return html
    .replace(/data-lucide="twitter"/g,  'data-lucide="x"')
    .replace(/data-lucide="github"/g,   'data-lucide="code-2"')
    .replace(/data-lucide="linkedin"/g, 'data-lucide="briefcase"')
    .replace(/https:\/\/unpkg\.com\/lucide@latest/g, 'https://unpkg.com/lucide@0.263.1');
}

// ── CDN script cache — fetched in parent, injected inline ────────
// Brave browser blocks CDN scripts inside srcdoc iframes.
// Fetch in parent page context (allowed), then inject as inline text.
const _scriptCache = new Map<string, string>();
async function fetchScript(url: string): Promise<string> {
  if (_scriptCache.has(url)) return _scriptCache.get(url)!;
  try {
    const res = await fetch(url);
    const text = res.ok ? await res.text() : '';
    if (text) _scriptCache.set(url, text);
    return text;
  } catch { return ''; }
}
const CDN = {
  react: 'https://unpkg.com/react@18/umd/react.development.js',
  reactDom: 'https://unpkg.com/react-dom@18/umd/react-dom.development.js',
  babel: 'https://unpkg.com/@babel/standalone/babel.min.js',
  tailwind: 'https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css',
};

function buildSrcdocInline(
  artifact: Artifact,
  reactTxt: string, reactDomTxt: string, babelTxt: string, tailwindTxt: string,
): string {
  let lang = (artifact.language ?? '').toLowerCase();
  const raw = artifact.content ?? '';

  if (['javascript', 'js', 'typescript', 'ts'].includes(lang)) {
    const hasJSX = /<[A-Z][A-Za-z0-9]*[\s\/>]|<\/[A-Za-z][A-Za-z0-9]*>/.test(raw);
    const hasReact = /import\s+.*[Rr]eact|from\s+['"]react['"]|useState|useEffect|useRef/.test(raw);
    const hasReturnJSX = /return\s*\(\s*<|=>\s*<[A-Z]/.test(raw);
    if ((hasJSX && hasReact) || hasReturnJSX) lang = lang === 'typescript' || lang === 'ts' ? 'tsx' : 'jsx';
  }

  const clean = raw
    .replace(/^export\s+default\s+(\w+)\s*;?\s*$/gm, '/* $1 */')
    .replace(/^export\s+default\s+/gm, '')
    .replace(/^export\s+(const|let|var|function|class)\s+/gm, '$1 ')
    .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
    // FIX: multiline import stripping (framer-motion, lucide-react span multiple lines)
    .replace(/import\s+(?:type\s+)?\{[\s\S]*?\}\s*from\s*['"][^'"]+['"]\s*;?/g, '')
    .replace(/import\s+\*\s+as\s+\w+\s+from\s*['"][^'"]+['"]\s*;?/g, '')
    .replace(/import\s+\w+\s*,\s*\{[\s\S]*?\}\s*from\s*['"][^'"]+['"]\s*;?/g, '')
    .replace(/import\s+\w+\s+from\s*['"][^'"]+['"]\s*;?/g, '')
    .replace(/import\s+['"][^'"]+['"]\s*;?/g, '');

  const base = `<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:system-ui,sans-serif;background:#0b0f1a;color:#e4e8f0;min-height:100vh}.sx-err{color:#f87171;background:rgba(248,113,113,.08);padding:14px;border-radius:8px;border:1px solid rgba(248,113,113,.25);font-family:monospace;font-size:13px;white-space:pre-wrap;margin:12px}</style>`;

  const motionStub = `window.motion=new Proxy({},{get:(_,tag)=>React.forwardRef(({children,...p},ref)=>React.createElement(tag||'div',{...p,ref},children))});window.AnimatePresence=({children})=>children;window.useAnimation=()=>({start:()=>{},stop:()=>{}});window.useInView=()=>true;window.useScroll=()=>({scrollY:{get:()=>0}});window.useSpring=v=>v;window.useTransform=v=>v;
// ── Lucide-React icon stubs ───────────────────────────────────────
// All imports are stripped from user code. These stubs provide every
// common icon as a simple SVG so components render without ReferenceError.
(function(){
  function _mk(path){return function(p){var s=p&&p.size||24,c=p&&p.color||'currentColor',w=p&&p.strokeWidth||2,n=p&&p.className||'';return React.createElement('svg',{xmlns:'http://www.w3.org/2000/svg',width:s,height:s,viewBox:'0 0 24 24',fill:'none',stroke:c,strokeWidth:w,strokeLinecap:'round',strokeLinejoin:'round',className:n},path.map(function(d,i){return React.createElement('path',{key:i,d:d})}));}}
  var icons={
    ShoppingBag:_mk(['M6 2L3 6v14a2 2 0 002 2h14a2 2 0 002-2V6l-3-4z','M3 6h18','M16 10a4 4 0 01-8 0']),
    ShoppingCart:_mk(['M9 22c.55 0 1-.45 1-1s-.45-1-1-1-1 .45-1 1 .45 1 1 1z','M20 22c.55 0 1-.45 1-1s-.45-1-1-1-1 .45-1 1 .45 1 1 1z','M1 1h4l2.68 13.39a2 2 0 001.99 1.61h9.72a2 2 0 001.99-1.75L23 6H6']),
    Menu:_mk(['M3 12h18','M3 6h18','M3 18h18']),
    X:_mk(['M18 6L6 18','M6 6l12 12']),
    Search:_mk(['M21 21l-6-6','M11 18a7 7 0 100-14 7 7 0 000 14z']),
    User:_mk(['M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2','M12 11a4 4 0 100-8 4 4 0 000 8z']),
    Heart:_mk(['M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z']),
    Star:_mk(['M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z']),
    ArrowRight:_mk(['M5 12h14','M12 5l7 7-7 7']),
    ArrowLeft:_mk(['M19 12H5','M12 19l-7-7 7-7']),
    ChevronRight:_mk(['M9 18l6-6-6-6']),
    ChevronLeft:_mk(['M15 18l-6-6 6-6']),
    ChevronDown:_mk(['M6 9l6 6 6-6']),
    ChevronUp:_mk(['M18 15l-6-6-6 6']),
    Home:_mk(['M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z','M9 22V12h6v10']),
    Settings:_mk(['M12 15a3 3 0 100-6 3 3 0 000 6z','M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z']),
    Instagram:_mk(['M16 2H8a6 6 0 00-6 6v8a6 6 0 006 6h8a6 6 0 006-6V8a6 6 0 00-6-6z','M12 16a4 4 0 100-8 4 4 0 000 8z','M17.5 6.5h.01']),
    Twitter:_mk(['M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z']),
    Facebook:_mk(['M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z']),
    Mail:_mk(['M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z','M22 6l-10 7L2 6']),
    Phone:_mk(['M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07 19.5 19.5 0 01-6-6 19.79 19.79 0 01-3.07-8.67A2 2 0 014.11 2h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L8.09 9.91a16 16 0 006 6l1.27-1.27a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 16.92z']),
    MapPin:_mk(['M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0118 0z','M12 13a3 3 0 100-6 3 3 0 000 6z']),
    Plus:_mk(['M12 5v14','M5 12h14']),
    Minus:_mk(['M5 12h14']),
    Check:_mk(['M20 6L9 17l-5-5']),
    Bell:_mk(['M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9','M13.73 21a2 2 0 01-3.46 0']),
    Globe:_mk(['M12 22a10 10 0 100-20 10 10 0 000 20z','M2 12h20','M12 2a15.3 15.3 0 010 20','M12 2a15.3 15.3 0 000 20']),
    Zap:_mk(['M13 2L3 14h9l-1 8 10-12h-9l1-8z']),
    Award:_mk(['M12 15a7 7 0 100-14 7 7 0 000 14z','M8.21 13.89L7 23l5-3 5 3-1.21-9.12']),
    Gift:_mk(['M20 12v10H4V12','M2 7h20v5H2z','M12 22V7','M12 7H7.5a2.5 2.5 0 010-5C11 2 12 7 12 7z','M12 7h4.5a2.5 2.5 0 000-5C13 2 12 7 12 7z']),
    Truck:_mk(['M1 3h15v13H1z','M16 8h4l3 3v5h-7V8z','M5.5 21a2.5 2.5 0 100-5 2.5 2.5 0 000 5z','M18.5 21a2.5 2.5 0 100-5 2.5 2.5 0 000 5z']),
    Tag:_mk(['M20.59 13.41l-7.17 7.17a2 2 0 01-2.83 0L2 12V2h10l8.59 8.59a2 2 0 010 2.82z','M7 7h.01']),
    Clock:_mk(['M12 22a10 10 0 100-20 10 10 0 000 20z','M12 6v6l4 2']),
    Calendar:_mk(['M19 4H5a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2V6a2 2 0 00-2-2z','M16 2v4','M8 2v4','M3 10h18']),
    Upload:_mk(['M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4','M17 8l-5-5-5 5','M12 3v12']),
    Download:_mk(['M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4','M7 10l5 5 5-5','M12 15V3']),
    Share2:_mk(['M18 8a3 3 0 100-6 3 3 0 000 6z','M6 15a3 3 0 100-6 3 3 0 000 6z','M18 20a3 3 0 100-6 3 3 0 000 6z','M8.59 13.51l6.83 3.98','M15.41 6.51l-6.82 3.98']),
    ExternalLink:_mk(['M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6','M15 3h6v6','M10 14L21 3']),
    Eye:_mk(['M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z','M12 15a3 3 0 100-6 3 3 0 000 6z']),
    Lock:_mk(['M19 11H5a2 2 0 00-2 2v7a2 2 0 002 2h14a2 2 0 002-2v-7a2 2 0 00-2-2z','M7 11V7a5 5 0 0110 0v4']),
    Linkedin:_mk(['M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6z','M2 9h4v12H2z','M4 6a2 2 0 100-4 2 2 0 000 4z']),
    Youtube:_mk(['M22.54 6.42a2.78 2.78 0 00-1.95-1.96C18.88 4 12 4 12 4s-6.88 0-8.59.46a2.78 2.78 0 00-1.95 1.96A29 29 0 001 12a29 29 0 00.46 5.58 2.78 2.78 0 001.95 1.95C5.12 20 12 20 12 20s6.88 0 8.59-.47a2.78 2.78 0 001.95-1.95A29 29 0 0023 12a29 29 0 00-.46-5.58z','M9.75 15.02l5.75-3.02-5.75-3.02v6.04z']),
    Code:_mk(['M16 18l6-6-6-6','M8 6l-6 6 6 6']),
    Copy:_mk(['M20 9H11a2 2 0 00-2 2v9a2 2 0 002 2h9a2 2 0 002-2v-9a2 2 0 00-2-2z','M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1']),
    Edit:_mk(['M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7','M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z']),
    Trash:_mk(['M3 6h18','M8 6V4h8v2','M19 6l-1 14H6L5 6']),
    RefreshCw:_mk(['M23 4v6h-6','M1 20v-6h6','M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15']),
    Filter:_mk(['M22 3H2l8 9.46V19l4 2v-8.54L22 3z']),
    Grid:_mk(['M3 3h7v7H3z','M14 3h7v7h-7z','M3 14h7v7H3z','M14 14h7v7h-7z']),
    List:_mk(['M8 6h13','M8 12h13','M8 18h13','M3 6h.01','M3 12h.01','M3 18h.01']),
    Info:_mk(['M12 22a10 10 0 100-20 10 10 0 000 20z','M12 16v-4','M12 8h.01']),
    AlertCircle:_mk(['M12 22a10 10 0 100-20 10 10 0 000 20z','M12 8v4','M12 16h.01']),
    CheckCircle:_mk(['M22 11.08V12a10 10 0 11-5.93-9.14','M22 4L12 14.01l-3-3']),
    XCircle:_mk(['M12 22a10 10 0 100-20 10 10 0 000 20z','M15 9l-6 6','M9 9l6 6']),
    Loader:_mk(['M12 2v4','M12 18v4','M4.93 4.93l2.83 2.83','M16.24 16.24l2.83 2.83','M2 12h4','M18 12h4','M4.93 19.07l2.83-2.83','M16.24 7.76l2.83-2.83']),
    TrendingUp:_mk(['M23 6l-9.5 9.5-5-5L1 18','M17 6h6v6']),
    TrendingDown:_mk(['M23 18l-9.5-9.5-5 5L1 6','M17 18h6v-6']),
    DollarSign:_mk(['M12 1v22','M17 5H9.5a3.5 3.5 0 100 7h5a3.5 3.5 0 110 7H6']),
    CreditCard:_mk(['M21 4H3a2 2 0 00-2 2v12a2 2 0 002 2h18a2 2 0 002-2V6a2 2 0 00-2-2z','M1 10h22']),
    Package:_mk(['M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 001 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z','M3.27 6.96L12 12.01l8.73-5.05','M12 22.08V12']),
    Layers:_mk(['M12 2L2 7l10 5 10-5-10-5z','M2 17l10 5 10-5','M2 12l10 5 10-5']),
  };
  Object.keys(icons).forEach(function(n){if(!window[n])window[n]=icons[n];});
})();`;

  const localStorageShim = `try{localStorage.setItem('sx','1');localStorage.removeItem('sx');}catch(e){Object.defineProperty(window,'localStorage',{value:{_d:{},setItem(k,v){this._d[k]=v},getItem(k){return this._d[k]??null},removeItem(k){delete this._d[k]},clear(){this._d={}}}});}`;

  const rootDetect = `
// Register default export so rootDetect can find it (Babel scope → window)
if(typeof __sx_root!=='undefined')window.__sx_default=__sx_root;
var _pref=['App','Component','Counter','Dashboard','Page','Main','Home','Index',
  'Root','Portfolio','Landing','Layout','Screen','View','Widget','Hero',
  'Profile','Showcase','Form','Modal','Card'];
// Only check window.__sx_default (registered above) and well-known names.
// NO generic window scan — it picks up CDN library functions → Illegal constructor.
var _Root=window.__sx_default||null;
if(!_Root){for(var _i=0;_i<_pref.length;_i++){var _c=window[_pref[_i]];if(typeof _c==='function'&&!_c.toString().includes('[native code]')){_Root=_c;break;}}}
if(_Root){try{ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(_Root));}catch(e){document.getElementById('root').innerHTML='<div class="sx-err">Render error: '+e.message+'</div>';}}
else{document.getElementById('root').innerHTML='<div class="sx-err" style="padding:20px"><strong>No component found.</strong><br/>Make sure your component name starts with a capital letter and is the default export.</div>'}`;

  // Extract default export name to register inside Babel scope
  const _inlineExport = raw.match(/export\s+default\s+(?:function\s+|class\s+)?(\w+)/);
  const _inlineName = (_inlineExport && !['function','class','const','let','var'].includes(_inlineExport[1]))
    ? _inlineExport[1] : null;
  // Registration: sets both window.__sx_default (for rootDetect) and __sx_root (local ref)
  const _inlineReg = _inlineName
    ? `try{var __sx_root=${_inlineName};window.__sx_default=${_inlineName};}catch(_e){}`
    : `var __sx_root=undefined;`;

  const hooks = `const {useState,useEffect,useRef,useCallback,useMemo,useReducer,useContext,createContext,Fragment,memo}=React;`;

  const sc = (txt: string) => `<script>${txt}<\/script>`;
  const head = [
    '<!DOCTYPE html><html><head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<base target="_blank"/>',
    reactTxt ? sc(reactTxt) : '<script src="https://unpkg.com/react@18/umd/react.development.js"><\/script>',
    reactDomTxt ? sc(reactDomTxt) : '<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"><\/script>',
    babelTxt ? sc(babelTxt) : '<script src="https://unpkg.com/@babel/standalone/babel.min.js"><\/script>',
    tailwindTxt ? `<style>${tailwindTxt}<\/style>` : '',
    sc(localStorageShim + motionStub),
    base,
    '<style>body{padding:16px}<\/style>',
    '<\/head><body><div id="root"><\/div>',
  ].join('');
  const errHandler = `<script>window.onerror=function(m){document.body.innerHTML='<div class=\"sx-err\">'+m+'<\/div>';};<\/script>`;
  const babelScript = `<script type="text/babel">try{${hooks}${clean}${_inlineReg}${rootDetect}}catch(e){document.body.innerHTML='<div class=\"sx-err\">'+e.message+'<\/div>';}<\/script>`;
  return head + errHandler + babelScript + '<\/body><\/html>';
}


const PreviewPane = memo(({ artifact }: { artifact: Artifact }) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [loaded, setLoaded] = useState(false);
  const [errMsg, setErrMsg] = useState('');
  const [fetching, setFetching] = useState(false);
  const [fullContent, setFullContent] = useState(artifact.content ?? '');
  const lang = (artifact.language ?? '').toLowerCase();

  // When artifact changes, reset and check if we need to fetch content
  useEffect(() => {
    setLoaded(false);
    setErrMsg('');
    const c = artifact.content ?? '';
    if (c.trim() === '') {
      // Content not loaded yet — fetch it from DB
      setFetching(true);
      loadArtifactContent(artifact.id).then(fetched => {
        setFullContent(fetched);
        setFetching(false);
      }).catch(() => {
        setFetching(false);
        setFullContent('');
      });
    } else {
      setFullContent(c);
    }
  }, [artifact.id, artifact.content]);

  // Set srcdoc once we have content — async for React to bypass CDN blocking
  useEffect(() => {
    if (fetching || fullContent.trim() === '') return;
    const lang = (artifact.language ?? '').toLowerCase();
    const isReact = ['jsx', 'tsx'].includes(lang) ||
      (['javascript', 'js', 'typescript', 'ts'].includes(lang) &&
        /import.*[Rr]eact|from\s+['"]react['"]|useState|useEffect/.test(fullContent) &&
        /<[A-Z][A-Za-z0-9]*[\s\/>]|return\s*\(\s*</.test(fullContent));
    setLoaded(false);
    if (isReact) {
      (async () => {
        try {
          const [rTxt, rdTxt, bTxt, twTxt] = await Promise.all([
            fetchScript(CDN.react), fetchScript(CDN.reactDom),
            fetchScript(CDN.babel), fetchScript(CDN.tailwind),
          ]);
          if (iframeRef.current)
            iframeRef.current.srcdoc = fixLucideIcons(buildSrcdocInline(
              { ...artifact, content: fullContent }, rTxt, rdTxt, bTxt, twTxt
            ));
        } catch (e: any) { setErrMsg(e.message || 'Preview failed'); }
      })();
    } else {
      try {
        if (iframeRef.current)
          iframeRef.current.srcdoc = fixLucideIcons(buildSrcdoc({ ...artifact, content: fullContent }));
      } catch (e: any) { setErrMsg(e.message || 'Preview failed'); }
    }
  }, [fullContent, fetching, artifact.language, artifact.type]);

  if (errMsg) return <div style={{ padding: 20, color: '#f87171', fontFamily: 'monospace', fontSize: 13 }}>Preview error: {errMsg}</div>;

  const isLoading = fetching || (!loaded && fullContent.trim() !== '');
  const isEmpty = !fetching && fullContent.trim() === '';

  return (
    <div className="ap-preview-container" style={{ flex: 1, overflow: 'hidden', height: '100%', minHeight: 0 }}>
      {(fetching || !loaded) && (
        <div className="ap-preview-loading">
          <div className="ap-spinner" />
          <span>
            {fetching ? 'Loading content…'
              : lang === 'python' || lang === 'py' ? 'Loading Python runtime…'
                : 'Rendering…'}
          </span>
        </div>
      )}
      {isEmpty && !fetching && (
        <div className="ap-preview-loading">
          <span style={{ color: 'var(--text-secondary)', fontSize: 13 }}>No content available</span>
        </div>
      )}
      <iframe
        key={artifact.id}
        ref={iframeRef}
        className={`ap-preview-iframe${loaded ? ' ap-preview-iframe--visible' : ''}`}
        sandbox="allow-scripts allow-same-origin allow-popups allow-forms allow-modals allow-pointer-lock"
        title={artifact.title}
        onLoad={() => setTimeout(() => setLoaded(true), 50)}
        onError={() => setErrMsg('Failed to load preview')}
        style={{ width: '100%', height: '100%', border: 'none', display: 'block', backgroundColor: '#0a0a0f' }} />
    </div>
  );
});

// ── Image Viewer ──────────────────────────────────────────────────
// FIX: Loads image content if empty (metadataOnly initial load)
const ImageViewer = memo(({ artifact }: { artifact: Artifact }) => {
  const [imgContent, setImgContent] = useState(artifact.content ?? '');
  const [fetching, setFetching] = useState(false);

  useEffect(() => {
    const c = artifact.content ?? '';
    if (c.trim() === '') {
      setFetching(true);
      loadArtifactContent(artifact.id).then(fetched => {
        setImgContent(fetched);
        setFetching(false);
      }).catch(() => setFetching(false));
    } else {
      setImgContent(c);
    }
  }, [artifact.id, artifact.content]);

  const src = getImageSrc(imgContent, artifact.title);
  return (
    <div className="ap-code-viewer" style={{ display: 'flex', flexDirection: 'column' }}>
      <div className="ap-code-toolbar">
        <div className="ap-code-meta"><span className="ap-code-icon">🖼️</span><span className="ap-code-lang">Generated Image</span></div>
        <div className="ap-code-actions"><button className="ap-action-btn" onClick={() => { const a = document.createElement('a'); a.href = src; a.download = artifact.title || 'image.png'; document.body.appendChild(a); a.click(); document.body.removeChild(a); }}><Icons.Download className="icon-12" /><span>Download</span></button></div>
      </div>
      <div className="ap-code-scroll" style={{ padding: 20, display: 'flex', justifyContent: 'center', alignItems: 'center', flex: 1, background: '#000' }}>
        {fetching ? (
          <div className="ap-spinner" />
        ) : src ? (
          <img src={src} alt={artifact.title} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', borderRadius: 8, boxShadow: '0 4px 20px rgba(0,0,0,0.5)' }} />
        ) : (
          <div style={{ color: '#6b7280', fontSize: 13 }}>Image data unavailable</div>
        )}
      </div>
    </div>
  );
});

// ── History Pane ──────────────────────────────────────────────────
const HistoryPane = memo(({ artifacts, diagrams, images, activeId, onSelect, onDelete }: { artifacts: Artifact[]; diagrams: Artifact[]; images: Artifact[]; activeId: string | null; onSelect: (id: string) => void; onDelete: (id: string) => void; }) => {
  const all = [...artifacts, ...diagrams, ...images];
  if (all.length === 0) return <div className="ap-history-empty"><div className="ap-history-empty-icon">📂</div><p className="ap-history-empty-title">No artifacts yet</p><p className="ap-history-empty-sub">Code files over 20 lines appear here instead of in the chat bubble.</p></div>;

  const renderSection = (items: Artifact[], label: string) => {
    if (!items.length) return null;
    return (<>
      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.1em', color: 'var(--text-secondary)', padding: '8px 12px 4px', opacity: 0.7 }}>{label}</div>
      {items.map(a => (
        <div key={a.id} className={`ap-history-item${a.id === activeId ? ' ap-history-item--active' : ''}`} onClick={() => onSelect(a.id)}>
          <span className="ap-history-item-icon">{fileIcon(a.language)}</span>
          <div className="ap-history-item-info"><div className="ap-history-item-title">{a.title}</div><div className="ap-history-item-meta">{langLabel(a.language)} · {a.lineCount} lines</div></div>
          <button className="ap-history-item-delete" onClick={e => { e.stopPropagation(); onDelete(a.id); }} title="Delete"><svg viewBox="0 0 16 16" style={{ width: 12, height: 12 }} fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M2 2l12 12M14 2L2 14" /></svg></button>
        </div>
      ))}
    </>);
  };

  return <div className="ap-history-list">{renderSection(artifacts, 'Code Artifacts')}{renderSection(diagrams, 'Diagrams')}{renderSection(images, 'Images')}</div>;
});

// ═══════════════════════════════════════════════════════════════════
// MAIN PANEL
// ═══════════════════════════════════════════════════════════════════
interface ArtifactPanelProps { onWidthChange?: (width: number) => void; }

const ArtifactPanel: React.FC<ArtifactPanelProps> = ({ onWidthChange }) => {
  const { artifacts, diagrams, images, activeId, panelOpen, activeArtifact, openArtifact, closePanel } = useArtifacts();
  const [tab, setTab] = useState<PanelTab>('code');
  const [width, setWidth] = useState(480);
  const panelRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef<{ startX: number; startW: number } | null>(null);
  const totalCount = artifacts.length + diagrams.length + images.length;

  useEffect(() => { if (activeId) setTab('code'); }, [activeId]);

  // Listen for direct open-artifact events from ArtifactCard clicks.
  // This is a reliable fallback for when Suspense/lazy mounting causes
  // the store subscription to miss the initial setActiveArtifact call.
  useEffect(() => {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail as { id: string };
      if (detail?.id) {
        openArtifact(detail.id);
        setTab('code');
      }
    };
    window.addEventListener('sedrex:open-artifact', handler);
    return () => window.removeEventListener('sedrex:open-artifact', handler);
  }, [openArtifact]);
  useEffect(() => { onWidthChange?.(panelOpen ? width : 0); }, [panelOpen, width, onWidthChange]);
  useEffect(() => {
    const h = (e: KeyboardEvent) => { if (e.key === 'Escape' && panelOpen) { e.preventDefault(); closePanel(); } };
    document.addEventListener('keydown', h);
    return () => document.removeEventListener('keydown', h);
  }, [panelOpen, closePanel]);

  const startDrag = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    dragRef.current = { startX: e.clientX, startW: width };
    document.body.style.cursor = 'col-resize'; document.body.style.userSelect = 'none';
    const onMove = (ev: MouseEvent) => { if (!dragRef.current) return; setWidth(Math.max(340, Math.min(800, dragRef.current.startW + dragRef.current.startX - ev.clientX))); };
    const onUp = () => { dragRef.current = null; document.body.style.cursor = ''; document.body.style.userSelect = ''; document.removeEventListener('mousemove', onMove); document.removeEventListener('mouseup', onUp); };
    document.addEventListener('mousemove', onMove); document.addEventListener('mouseup', onUp);
  }, [width]);

  if (!panelOpen) return null;

  const artifact = activeArtifact;
  const isDiagram = artifact ? isDiagramArtifact(artifact) : false;
  const isImage = artifact?.type === 'image';

  return (
    <>
      <div className="ap-resize-handle" onMouseDown={startDrag} title="Drag to resize" />
      <div ref={panelRef} className="ap-root" style={{ width }}>
        <div className="ap-header">
          <div className="ap-header-left">
            {artifact ? (<><span className="ap-header-icon">{fileIcon(artifact.language)}</span><div className="ap-header-info"><span className="ap-header-title">{artifact.title}</span>{artifact.filePath && <span className="ap-header-path">{artifact.filePath}</span>}</div></>) : <span className="ap-header-title">Artifacts</span>}
          </div>
          <div className="ap-header-right">
            <div className="ap-tabs">
              <button className={`ap-tab${tab === 'code' ? ' ap-tab--active' : ''}`} onClick={() => setTab('code')}>
                <svg viewBox="0 0 14 14" style={{ width: 11, height: 11 }} fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 3L1 7l3 4M10 3l3 4-3 4M8 1L6 13" /></svg>
                {isDiagram ? 'Diagram' : isImage ? 'Image' : 'Code'}
              </button>
              {!isDiagram && !isImage && (
                <button className={`ap-tab${tab === 'preview' ? ' ap-tab--active' : ''}`} onClick={() => setTab('preview')} title="Live preview">
                  <svg viewBox="0 0 14 14" style={{ width: 11, height: 11 }} fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="7" cy="7" r="2.5" /><path d="M1 7s2-5 6-5 6 5 6 5-2 5-6 5-6-5-6-5z" /></svg>
                  Preview{artifact && <span className="ap-tab-live">●</span>}
                </button>
              )}
              <button className={`ap-tab${tab === 'history' ? ' ap-tab--active' : ''}`} onClick={() => setTab('history')}>
                <svg viewBox="0 0 14 14" style={{ width: 11, height: 11 }} fill="none" stroke="currentColor" strokeWidth="1.5"><rect x="1" y="1" width="12" height="12" rx="1.5" /><path d="M4 5h6M4 8h4" /></svg>
                History{totalCount > 0 && <span className="ap-tab-badge">{totalCount}</span>}
              </button>
            </div>
            <button className="ap-close-btn" onClick={closePanel} title="Close (Esc)"><Icons.X className="icon-14" /></button>
          </div>
        </div>
        <div className="ap-content">
          {tab === 'code' && isImage && artifact && <ImageViewer artifact={artifact} />}
          {tab === 'code' && isDiagram && artifact && <DiagramViewer artifact={artifact} />}
          {tab === 'code' && !isDiagram && !isImage && artifact && <CodeViewer artifact={artifact} onSwitchToPreview={() => setTab('preview')} />}
          {tab === 'code' && !artifact && <div className="ap-empty"><div className="ap-empty-icon">📄</div><p className="ap-empty-title">No artifact selected</p><p className="ap-empty-sub">Pick one from History or ask SEDREX to generate code.</p></div>}
          {tab === 'preview' && artifact && <PreviewPane artifact={artifact} />}
          {tab === 'preview' && !artifact && <div className="ap-empty"><div className="ap-empty-icon">👁️</div><p className="ap-empty-title">No artifact selected</p><p className="ap-empty-sub">Select an artifact to preview it.</p></div>}
          {tab === 'history' && <HistoryPane artifacts={artifacts} diagrams={diagrams} images={images} activeId={activeId} onSelect={id => { openArtifact(id); setTab('code'); }} onDelete={deleteArtifact} />}
        </div>
      </div>
    </>
  );
};

export default ArtifactPanel;